export interface IMenuItem {
  name: string;
  icon?: string;
  path?: string;
  children?: Array<IMenuItem>;
  allowedRoles?: string[];
  allowedPermissions?: string[];
  resource?: string;
}

export const MENU: IMenuItem[] = [
  {
    name: "Dashboard",
    icon: "fas fa-tachometer-alt nav-icon",
    path: "/dashboard",
    allowedPermissions: ["view_dashboard"],
  },
  {
    name: "Users",
    icon: "fas fa-wrench nav-icon",
    path: "/users",
    allowedRoles: ["tenant_admin", "superadmin", "system_admin"],
    resource: "users",
  },
  {
    name: "Organizations",
    icon: "fas fa-building nav-icon",
    path: "/tenants",
    allowedRoles: ["superadmin", "system_admin"],
    resource: "tenants",
  },
  {
    name: "Subscription",
    icon: "fas fa-credit-card nav-icon",
    path: "/subscription",
    allowedRoles: ["tenant_admin"],
  },
  {
    name: "Roles",
    icon: "fas fa-user-shield nav-icon",
    path: "/roles",
    allowedRoles: ["tenant_admin", "superadmin", "system_admin"],
    allowedPermissions: ["manage_roles", "view_roles"],
  },
  {
    name: "User Count",
    icon: "fas fa-user nav-icon",
    path: "/user-count",
    allowedRoles: ["tenant_admin", "superadmin", "system_admin"],
    allowedPermissions: ["view_user_count"],
    resource: "user_count",
  },
  {
    name: "Member List",
    icon: "fas fa-users nav-icon",
    path: "/member-list",
    allowedPermissions: ["view_members"],
    resource: "members",
  },

  {
    name: "MP Public Problem",
    icon: "fas fa-exclamation-circle nav-icon",
    path: "/mp-public-problem",
    resource: "mp_public_problems",
  },
  {
    name: "Assembly Issue",
    icon: "fas fa-university nav-icon",
    resource: "assembly_issues",
    children: [
      {
        name: "All Issues",
        icon: "fas fa-list nav-icon",
        path: "/assembly-issue",
        resource: "assembly_issues",
      },
      {
        name: "Myassembly0",
        icon: "far fa-circle nav-icon",
        path: "/myassembly0",
        resource: "assembly_issues",
      },
      {
        name: "Myassembly2",
        icon: "far fa-circle nav-icon",
        path: "/myassembly2",
        resource: "assembly_issues",
      },
      {
        name: "Myassembly3",
        icon: "far fa-circle nav-icon",
        path: "/myassembly3",
        resource: "assembly_issues",
      },
    ],
  },
  {
    name: "Vidhasabha Samiti",
    icon: "fas fa-building nav-icon",
    allowedPermissions: ["view_vidhan_sabha_samiti"],
    resource: "vidhan_sabha_samiti",
    children: [
      {
        name: "Ganesh-Samiti",
        icon: "far fa-circle nav-icon",
        path: "/vidhasabha-samiti/ganesh-samiti",
        resource: "ganesh_samiti",
      },
      {
        name: "Tenkar-Samiti",
        icon: "fas fa-water nav-icon",
        path: "/vidhasabha-samiti/tenkar-samiti",
        resource: "tenkar_samiti",
      },
      {
        name: "DP-Samiti",
        icon: "fas fa-bolt nav-icon",
        path: "/vidhasabha-samiti/dp-samiti",
        resource: "dp_samiti",
      },
      {
        name: "Mandir-Samiti",
        icon: "fas fa-monument nav-icon",
        path: "/vidhasabha-samiti/mandir-samiti",
        resource: "mandir_samiti",
      },
      {
        name: "Bhagoria-Samiti",
        icon: "fas fa-music nav-icon",
        path: "/vidhasabha-samiti/bhagoria-samiti",
        resource: "bhagoria_samiti",
      },
      {
        name: "Nirman-Samiti",
        icon: "fas fa-hard-hat nav-icon",
        path: "/vidhasabha-samiti/nirman-samiti",
        resource: "nirman_samiti",
      },
      {
        name: "Booth-Samiti",
        icon: "fas fa-person-booth nav-icon",
        path: "/vidhasabha-samiti/booth-samiti",
        resource: "booth_samiti",
      },
      {
        name: "Block-Samiti",
        icon: "fas fa-cubes nav-icon",
        path: "/vidhasabha-samiti/block-samiti",
        resource: "block_samiti",
      },
    ],
  },
  {
    name: "Project Summary",
    icon: "fas fa-user-friends nav-icon",
    path: "/project-summary",
    resource: "projects",
  },
  {
    name: "Visitors",
    icon: "fas fa-id-badge nav-icon",
    path: "/visitors",
    resource: "visitors",
  },
  {
    name: "Events",
    icon: "fas fa-calendar-alt nav-icon",
    resource: "events",
    allowedPermissions: ["view_events"],
    children: [
      {
        name: "Event List",
        icon: "far fa-circle nav-icon",
        path: "/events",
        resource: "events",
      },
      {
        name: "Events Calendar",
        icon: "far fa-circle nav-icon",
        path: "/events/calendar",
        allowedPermissions: ["view_events_calendar"],
        resource: "events",
      },
    ],
  },
  {
    name: "Voter",
    icon: "fas fa-vote-yea nav-icon",
    path: "/voter",
    resource: "voters",
  },
  {
    name: "Samiti",
    icon: "fas fa-handshake nav-icon",
    path: "/samiti",
    allowedPermissions: ["view_samiti"],
    resource: "samiti",
  },
  {
    name: "District",
    icon: "fas fa-map-marker-alt nav-icon",
    path: "/districts",
    allowedPermissions: ["view_districts", "manage_districts"],
    resource: "districts",
  },
  {
    name: "Vidhan Sabha",
    icon: "fas fa-gavel nav-icon",
    path: "/vidhansabha",
    allowedPermissions: ["view_assemblies"],
    resource: "assemblies",
  },
  {
    name: "Block",
    icon: "fas fa-cubes nav-icon",
    path: "/blocks",
    allowedPermissions: ["view_blocks", "manage_blocks"],
    resource: "blocks",
  },
  {
    name: "Booth",
    icon: "fas fa-person-booth nav-icon",
    path: "/booths",
    allowedPermissions: ["view_booths", "manage_booths"],
    resource: "booths",
  },
  {
    name: "Panchayat",
    icon: "fas fa-users nav-icon",
    path: "/panchayat",
    allowedPermissions: ["view_panchayats", "manage_panchayats"],
    resource: "panchayats",
  },
  {
    name: "Village",
    icon: "fas fa-home nav-icon",
    path: "/villages",
    allowedPermissions: ["view_villages", "manage_villages"],
    resource: "villages",
  },
  {
    name: "Party",
    icon: "fas fa-flag nav-icon",
    path: "/party",
    allowedPermissions: ["view_parties"],
    resource: "parties",
  },
  {
    name: "Department",
    icon: "fas fa-building nav-icon",
    path: "/department",
    allowedPermissions: ["view_departments"],
    resource: "departments",
  },
  {
    name: "Worktype",
    icon: "fas fa-briefcase nav-icon",
    path: "/worktype",
    allowedPermissions: ["view_work_types"],
    resource: "work_types",
  },
  {
    name: "Sub Type of Work",
    icon: "fas fa-tasks nav-icon",
    path: "/sub-type-of-work",
    allowedPermissions: ["view_sub_work_types"],
    resource: "sub_work_types",
  },
  {
    name: "State",
    icon: "fas fa-map nav-icon",
    path: "/states",
    allowedPermissions: ["view_states", "manage_states"],
    resource: "states",
  },
  {
    name: "Division",
    icon: "fas fa-layer-group nav-icon",
    path: "/divisions",
    allowedPermissions: ["view_divisions", "manage_divisions"],
    resource: "divisions",
  },
  {
    name: "Parliament",
    icon: "fas fa-landmark nav-icon",
    path: "/parliaments",
    allowedPermissions: ["view_parliaments", "manage_parliaments"],
    resource: "parliaments",
  },
  {
    name: "Assembly",
    icon: "fas fa-columns nav-icon",
    path: "/assemblies",
    allowedPermissions: ["view_assemblies", "manage_assemblies"],
    resource: "assemblies",
  },

  {
    name: "Phone Directory",
    icon: "fas fa-address-book nav-icon",
    path: "/phone-directory",
    allowedPermissions: ["view_phone_directory"],
    resource: "phone_directory",
  },

  {
    name: "In Docs",
    icon: "fas fa-file-alt nav-icon",
    path: "/in-docs",
    allowedPermissions: ["view_in_docs"],
    resource: "in_docs",
  },
  {
    name: "Inward Register",
    icon: "fas fa-file-invoice nav-icon",
    path: "/inward-register",
    allowedPermissions: ["view_inward_register"],
    resource: "inward_register",
  },
  {
    name: "Dispatch Register",
    icon: "fas fa-paper-plane nav-icon",
    path: "/dispatch-register",
    allowedPermissions: ["view_dispatch_register"],
    resource: "dispatch_register",
  },
  {
    name: "Call Management",
    icon: "fas fa-phone nav-icon",
    path: "/call-management",
    allowedPermissions: ["view_call_management"],
    resource: "call_management",
  },
  {
    name: "Activity Management",
    icon: "fas fa-history nav-icon",
    allowedRoles: ["superadmin", "system_admin"],
    allowedPermissions: ["view_activity_logs", "view_user_activity_report"],
    resource: "activity_management",
    children: [
      {
        name: "Activity Logs",
        icon: "far fa-circle nav-icon",
        path: "/activity-management/activity-logs",
        resource: "activity_logs",
      },
      {
        name: "User Activity Report",
        icon: "fas fa-chart-line nav-icon",
        path: "/activity-management/user-activity-report",
        resource: "user_activity_report",
      },
    ],
  },
];
