require("dotenv").config();
const mongoose = require("mongoose");
const InDocs = require("./src/models/inDocsModel");

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB Connected for Seeding InDocs...");
  } catch (error) {
    console.error("MongoDB Connection Error:", error);
    process.exit(1);
  }
};

const seedInDocs = async () => {
  await connectDB();

  const NUMBER_OF_ENTRIES = 20;

  try {
    // Generate dummy data
    const entries = [];
    const subjects = [
      "Road Repair Request",
      "Water Pipeline Issue",
      "Electricity Bill Correction",
      "School Admission Inquiry",
      "New Park Proposal",
    ];
    const places = ["Zone 1", "Zone 2", "Zone 3", "Central Block", "East Wing"];

    for (let i = 0; i < NUMBER_OF_ENTRIES; i++) {
      const subject = subjects[Math.floor(Math.random() * subjects.length)];
      const place = places[Math.floor(Math.random() * places.length)];

      entries.push({
        issueNo: `IND-${new Date().getFullYear()}-${1000 + i}`,
        date: new Date(Date.now() - Math.floor(Math.random() * 10000000000)), // Random date in past year usually
        nameAddress: `Citizen ${i + 1}, House No ${10 + i}, Locality ${String.fromCharCode(65 + (i % 5))}`,
        place: place,
        subject: subject,
        documentsCount: `${Math.floor(Math.random() * 5) + 1}`,
        referenceIssueNo: `REF-${Math.floor(Math.random() * 1000)}`,
        receivedIssueNo: `REC-${Math.floor(Math.random() * 1000)}`,
        fileHeadNo: `FH-${Math.floor(Math.random() * 100)}`,
        stampReceived: `${Math.floor(Math.random() * 500)}/-`,
        remarks: "Generated by Seed Script",
      });
    }

    await InDocs.insertMany(entries);
    console.log(`Successfully seeded ${NUMBER_OF_ENTRIES} InDocs entries.`);
  } catch (error) {
    console.error("Error seeding InDocs:", error);
  } finally {
    mongoose.connection.close();
  }
};

seedInDocs();
