require("dotenv").config();
const mongoose = require("mongoose");
const InwardRegister = require("./src/models/inwardRegisterModel");

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB Connected for Seeding Inward Register...");
  } catch (error) {
    console.error("MongoDB Connection Error:", error);
    process.exit(1);
  }
};

const seedInwardRegister = async () => {
  await connectDB();

  const NUMBER_OF_ENTRIES = 20;

  try {
    const entries = [];

    for (let i = 0; i < NUMBER_OF_ENTRIES; i++) {
      const issueDate = new Date(
        Date.now() - Math.floor(Math.random() * 10000000000),
      );
      const receivedDate = new Date(
        issueDate.getTime() + Math.random() * 86400000 * 5,
      ); // Received 0-5 days later

      entries.push({
        issueNo: `IR-${new Date().getFullYear()}-${1000 + i}`,
        issueDate: issueDate,
        letterName: `Letter Type ${String.fromCharCode(65 + (i % 5))}`,
        letterReceivedDate: receivedDate,
        fromWhomReceived: `Sender ${i + 1}, Organization XYZ`,
        letterDescription: "Sample description of the received letter.",
        subject: `Subject of Letter ${i + 1}`,
        fileNo: `FILE-${Math.floor(Math.random() * 100)}`,
        receivedLetterNumber: `RLN-${Math.floor(Math.random() * 1000)}`,
        receivedLetterDate: new Date(
          receivedDate.getTime() - Math.random() * 86400000 * 10,
        ), // Dated before receipt
        replyToNumber: Math.random() > 0.5 ? `REPLY-${i}` : undefined,
        replyToDate: Math.random() > 0.5 ? new Date() : undefined,
        section: "General Administration",
        sentTo: "Manager",
        remarks: "Generated by Seed Script",
      });
    }

    await InwardRegister.insertMany(entries);
    console.log(
      `Successfully seeded ${NUMBER_OF_ENTRIES} Inward Register entries.`,
    );
  } catch (error) {
    console.error("Error seeding Inward Register:", error);
  } finally {
    mongoose.connection.close();
  }
};

seedInwardRegister();
